apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  releaseName: cilium
  interval: 5m
  timeout: 10m
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  chart:
    spec:
      chart: cilium
      version: "1.17.3"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 5m
  values:
    k8sServiceHost: 192.168.1.78
    k8sServicePort: 6443

    kubeProxyReplacement: true

    l2announcements:
      enabled: true

    externalIPs:
      enabled: true

    k8sClientRateLimit:
      qps: 50
      burst: 200

    operator:
      replicas: 1  # Uncomment this if you only have one node
      rollOutPods: true

    rollOutCiliumPods: true

    ingressController:
      enabled: true
      default: true
      loadbalancerMode: shared
      service:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.1.240
