apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium-config
  namespace: flux-system
spec:
  releaseName: cilium-config
  interval: 5m
  timeout: 10m
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  dependsOn:
    - name: cilium
      namespace: kube-system
  chart:
    spec:
      chart: cilium-config
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: cilium-config
        namespace: flux-system
      interval: 1m