# ip-pool.yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "first-pool"
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.1.240"
      stop: "192.168.1.249"