apiVersion: helm.toolkit.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  releaseName: headlamp
  interval: 5m
  timeout: 10m
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  dependsOn:
    - name: cilium
      namespace: kube-system
  chart:
    spec:
      chart: headlamp
      version: "0.30.1"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: headlamp
  values:
    fullnameOverride: "headlamp"
    
    resources:
      limits:
        memory: 256Mi
        cpu: 500m
      requests:
        memory: 128Mi
        cpu: 100m

    ingress:
      enabled: true
      className: cilium
      annotations:
        # cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: headlamp.lab.auren.io
          paths:
            - path: /
              pathType: Prefix
      # tls:
      #   - secretName: headlamp-tls
      #     hosts:
      #       - headlamp.lab.auren.fr 